### ISSUE TITLE
StatSig react native not working

### ISSUE THREAD

**Issue by sahil-ahuja-1** [statsig-io/react-native#1]
Hello! StatSig is not working with React Native for me.

The app builds find but adding StatsigProvider causes the app to crash

I'm using react native version 0.67.3 and react version 17.0.2

This has been happening for several months and has been a hard blocker from our company using your product. I'd appreciate any help getting this to work! Thanks :)

![Simulator Screen Shot - iPhone 13 - 2022-11-08 at 15 24 53](https://user-images.githubusercontent.com/101741806/200668396-867db582-d8a6-4e1f-93de-f31aa354531d.png)

**Comment by tore-statsig** [comment]
![image](https://user-images.githubusercontent.com/74584483/200689058-e2e3b3de-17b2-4a98-b3bb-620127a85a62.png)

Copying this code snippet which was shared in slack.  It looks like you are trying to do your own custom initialization path *and* use the provider, which wont work
