### ISSUE TITLE
Peer dependencies restrict react-native to 0.60.*

### ISSUE THREAD

**Issue by novemberborn** [statsig-io/react-native#3]
The following entry suggests that this SDK is **solely** compatible with React Native 0.60:

https://github.com/statsig-io/react-native/blob/50a5cafcb03c82a125e9040d2aba00b454816f71/package.json#L34

If it is a minimal version, it needs to be expressed as `>= 0.60`.

You can use https://semver.npmjs.com/ to compare the different specifiers.

**Comment by pyb4430** [comment]
I'm also facing this issue

**Comment by tore-statsig** [comment]
Ah, it used to be `>= 0.60`, I dont think that was an intentional change.  Thanks for the report, we will look into fixing this

**Comment by mljlynch** [comment]
Looks like this was fixed! Thanks 🥳

**Comment by tore-statsig** [comment]
Yes, meant to close this out.  Thanks for the report

https://github.com/statsig-io/react-native/releases/tag/4.15.0
